2022-04-20 13:44:38,498 [ERROR] _handle_response (http.py:51): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/users/@me, error: 401, 返回内容: b'{"message":"wrong bot token","code":11242}', trace_id:0d96f439a84632e3cb37b9a8ae3af703
2022-04-20 13:55:59,126 [ERROR] _handle_response (http.py:51): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/users/@me, error: 401, 返回内容: b'{"message":"wrong bot token","code":11242}', trace_id:8cf6dde622365afc678290894c271d4e
2022-04-20 13:58:03,501 [ERROR] _handle_response (http.py:51): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/users/@me, error: 401, 返回内容: b'{"message":"wrong bot token","code":11242}', trace_id:61c08c2e1f3e1757f8ff4699fb20462e
2022-04-20 13:59:14,861 [ERROR] _handle_response (http.py:51): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/users/@me, error: 401, 返回内容: b'{"message":"wrong bot token","code":11242}', trace_id:729ca000df05a9f3f974415635e40b9b
2022-04-20 14:00:53,956 [ERROR] _handle_response (http.py:51): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/users/@me, error: 401, 返回内容: b'{"message":"wrong bot token","code":11242}', trace_id:8ad707a027da07c587a60620de82ad84
2022-04-20 14:01:29,382 [ERROR] _handle_response (http.py:51): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/users/@me, error: 401, 返回内容: b'{"message":"wrong bot token","code":11242}', trace_id:222b7b482668772cebdb06d40067b87d
2022-04-20 16:34:01,804 [ERROR] _handle_response (http.py:51): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/channels/6jd41x5029, error: 401, 返回内容: b'{"message":"get guild id failed","code":11263}', trace_id:767f344642bfb72a00e346ac7a0a6612
2022-04-20 16:34:18,747 [ERROR] _handle_response (http.py:51): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/channels/4294837189, error: 401, 返回内容: b'{"message":"get guild id failed","code":11263}', trace_id:aab455ea97adbc49a633545f06c5cf9c
2022-04-20 16:37:56,922 [ERROR] _handle_response (http.py:51): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/channels/5440859059313954953, error: 401, 返回内容: b'{"message":"get guild id failed","code":11263}', trace_id:bd016790074cc838b581a3f2c623a07d
2022-04-20 16:47:30,733 [ERROR] _handle_response (http.py:51): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/channels/5463311/messages, error: 400, 返回内容: b'{"code":304018,"message":"websocket link does not exist"}', trace_id:909653288a4467e518d2646116ce1c7d
2022-04-20 17:17:44,677 [INFO] start (ws_session_manager.py:50): [连接管理]程序启动中...
2022-04-20 17:17:49,682 [INFO] new_connect (ws_session_manager.py:105): [连接管理]会话启动中...
2022-04-20 17:17:49,903 [INFO] identify (ws_client.py:111): [ws连接]鉴权中...
2022-04-20 17:17:50,149 [INFO] on_message (ws_client.py:73): [ws连接]鉴权成功
2022-04-20 17:17:50,149 [INFO] on_message (ws_client.py:78): [ws连接]程序启动成功！
2022-04-20 17:31:09,642 [INFO] start (ws_session_manager.py:50): [连接管理]程序启动中...
2022-04-20 17:31:14,645 [INFO] new_connect (ws_session_manager.py:105): [连接管理]会话启动中...
2022-04-20 17:31:14,962 [INFO] identify (ws_client.py:111): [ws连接]鉴权中...
2022-04-20 17:31:15,059 [INFO] on_message (ws_client.py:73): [ws连接]鉴权成功
2022-04-20 17:31:15,059 [INFO] on_message (ws_client.py:78): [ws连接]程序启动成功！
2022-04-20 17:31:34,128 [INFO] _at_message_handler (main.py:17): event AT_MESSAGE_CREATE,receive message <@!11379536499723901039>
2022-04-20 17:36:02,417 [INFO] _at_message_handler (main.py:17): event AT_MESSAGE_CREATE,receive message <@!11379536499723901039> 
2022-04-20 17:52:32,522 [INFO] _at_message_handler (main.py:17): event AT_MESSAGE_CREATE,receive message <@!11379536499723901039> 
2022-04-20 17:59:09,033 [INFO] _at_message_handler (main.py:17): event AT_MESSAGE_CREATE,receive message <@!11379536499723901039> Can you speak Chinese ?
2022-04-20 18:01:14,948 [INFO] on_close (ws_client.py:50): [ws连接]关闭, 返回码: 4009, 返回信息:Session timed out
2022-04-20 18:01:19,955 [INFO] new_connect (ws_session_manager.py:105): [连接管理]会话启动中...
2022-04-20 18:01:20,154 [INFO] reconnect (ws_client.py:140): [ws连接]重连启动中...
2022-04-20 18:05:57,506 [INFO] _at_message_handler (main.py:17): event AT_MESSAGE_CREATE,receive message <@!11379536499723901039>
2022-04-20 18:31:20,275 [INFO] on_close (ws_client.py:50): [ws连接]关闭, 返回码: 4009, 返回信息:Session timed out
2022-04-20 18:31:25,279 [INFO] new_connect (ws_session_manager.py:105): [连接管理]会话启动中...
2022-04-20 18:31:25,611 [INFO] reconnect (ws_client.py:140): [ws连接]重连启动中...
